[project]
name = "database"
version = "0.1.0"
description = "Shared database models and schemas"
requires-python = ">=3.11"
dependencies = [
    "sqlalchemy",
    "pgvector",
    "utils"
]

[tool.uv.sources]
utils = { workspace = true }
